name: .NET Desktop

on:
  workflow_dispatch:
    
jobs:
  build:
    name: Build and publish
    runs-on: windows-latest
    steps:
    - name: Check-out repository
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
 
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish --configuration Release --no-restore
      
    - name: Upload RouteManager Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: RouteManager
        path: D:\a\RouteManager\RouteManager\src\RouteManager\bin\Release\
